<?php
/**
* Custom Site Nav Walker
* - Adds custom attributes to site nav
* - Strips some extraneous classes generated by Wordpress
* - Replaces archive url with get_month_link #techdebt
*
* Based on: http://wordpress.stackexchange.com/q/14037/
*/
class Site_Nav_Walker extends Walker_Nav_Menu {
  /**
   * Start the element output.
   *
   * @param  string $output Passed by reference. Used to append additional content.
   * @param  object $item   Menu item data object.
   * @param  int $depth     Depth of menu item. May be used for padding.
   * @param  array $args    Additional strings.
   * @return void
   */
  function start_el( &$output, $item, $depth = 0, $args = array(), $id = 0 ) {
    
    /*
     * Re-write Wordpress default classes
     */
    $classes = empty ( $item->classes ) ? array () : (array) $item->classes;
    $li_class = 'site-nav__list-item';
    $is_current = in_array('current-menu-item', $classes);

    /*
     * The link $title
     */
    $title = apply_filters( 'the_title', $item->title, $item->ID );


    /*
     * Break two word $title values with <span>s for lower breakpoints
     */
    // if ( preg_match('/\s/', $title) ) :
    //   list( $first_word, $second_word ) = split(' ', $title);
    //   $title = $first_word . '<span class="site-nav__link--secondary"> ' . $second_word . '</span>';
    // endif;

    /*
     * Start $output
     */
    $output .= '<li class="' . esc_attr( $li_class ) .'">';

    /*
     * Define $attributes
     */
    $attributes = !$is_current ? 'class="site-nav__link"' : 'class="site-nav__link site-nav__link--active"';

    if ( !empty( $item->attr_title ) ) :
      $attributes .= ' title="'  . esc_attr( $item->attr_title ) .'"';
    endif;

    if ( !empty( $item->target ) ) :
      $attributes .= ' target="'  . esc_attr( $item->target ) .'"';
    endif;

    if ( !empty( $item->xfn ) ) :
      $attributes .= ' rel="'  . esc_attr( $item->xfn ) .'"';
    endif;

    if ( !empty( $item->url ) ) :
        $attributes .= ' href="'  . esc_attr( $item->url ) . '"';
    endif;

    /*
     * Build $item_output
     */
    $item_output = $args['before']
      . "<a $attributes>"
      . $args['link_before']
      . $title
      . '</a> '
      . $args['link_after']
      . $args['after'];

    /*
     * Finish building $output
     * Since $output is called by reference we don't need to return anything.
     */
    $output .= apply_filters(
      'walker_nav_menu_start_el',
      $item_output,
      $item,
      $depth,
      $args
    );
  }
}
